refactoring validation Activity
stone-payments/demo-sdk-android pull request #54
Opened 2024-08-29 21:04 UTC by laissdj49

2024-09-05 13:21 UTC, carvalhodj approved these changes

2024-09-05 16:57 UTC, rezzaghi approved these changes

2024-09-06 20:29 UTC, lomartins commented on app/src/main/java/br/com/stonesdk/sdkdemo/activities/ValidationActivity.kt
> +                }
Esse spinner pode ser removido. Não usamos mais ele pra definir o ambiente. Coloca apenas um texto mostrando qual é o ambiente.

2024-09-06 20:29 UTC, lomartins requested changes
Remover spinner pra selecionar ambiente.

2024-09-09 11:50 UTC, oliiveiraaGoncalves commented on app/build.gradle
> +    implementation 'com.google.accompanist:accompanist-permissions:0.35.0-alpha'
poderia aproveitar e adicionar o catalogs ao projeto

2024-09-09 11:50 UTC, oliiveiraaGoncalves commented on app/src/main/java/br/com/stonesdk/sdkdemo/activities/ValidationActivity.kt
> +        if (FeatureFlag.composeRefactorEnabled) {
Regra de apresentação coloca dentro do viewModel

2024-09-09 11:50 UTC, oliiveiraaGoncalves commented on app/build.gradle
> +    implementation 'com.google.accompanist:accompanist-permissions:0.35.0-alpha'
se possível tbm seria interessante migrar para o .kts

2024-09-09 13:00 UTC, lomartins commented on app/src/main/java/br/com/stonesdk/sdkdemo/activities/ValidationActivity.kt
> +        if (FeatureFlag.composeRefactorEnabled) {
Precisa mesmo dessa feature flag? Ao meu ver seria só migrar, como é demo não tem necessidade de feature flag.

2024-09-13 17:51 UTC, laissdj49 commented on app/src/main/java/br/com/stonesdk/sdkdemo/activities/ValidationActivity.kt
> +        if (FeatureFlag.composeRefactorEnabled) {
Não vou colocar a regra no viewModel agora pq ela é temporária , vou excluir.

2024-09-13 17:53 UTC, laissdj49 commented on app/build.gradle
> +    implementation 'com.google.accompanist:accompanist-permissions:0.35.0-alpha'
Sim, eu criei o tools mas vou enviar as alterações em outro pr pra n ficar muito cheio. Obrigada!!

2024-09-24 19:09 UTC, GabrielXs approved these changes

2024-09-27 09:12 UTC, merged